---
title: "NetworkPlot"
author: "Hilary"
date: "February 4, 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(gcookbook)
library(igraph)
madmen

m <- madmen[1:nrow(madmen) %% 2 == 1, ]
g <- graph.data.frame(m, directed=FALSE)

plot(g)


points <- graph(c(1,2, 4,5, 3,7, 8,1))
plot(points)

set.seed(6)
gu <- graph(c(1,2, 2,3, 2,4, 1,4, 5,5, 3,6), directed=FALSE)
# No labels
plot(gu, vertex.label=NA)

g <- graph.data.frame(madmen2, directed=TRUE)

plot(g, layout=layout.fruchterman.reingold, vertex.size=8, edge.arrow.size=0.5,
     vertex.label=NA)

gg <- graph.data.frame(madmen, directed=FALSE)
par(mar=c(0,0,0,0)) # Remove unnecessary margins
plot(gg, layout=layout.circle, vertex.size=8, vertex.label=NA)

#library(devtools)
#install_github('arcdiagram',  username='gastonstat')
library(arcdiagram)
star_graph = graph.star(10, mode="out")
star_graph
plot(star_graph)
star_edges = get.edgelist(star_graph)
star_edges
arcplot(star_edges)
arcplot(star_edges, show.nodes=TRUE, sorted=TRUE, decreasing=TRUE, las=1)
?arcplot

#cool arc diagram
set.seed(120)
arcplot(star_edges, ordering=sample(1:10), labels=paste("node",1:10,sep="-"),
        lwd.arcs=4*runif(10,.5,2), col.arcs=hsv(runif(9,0.6,0.8),alpha=0.4),
        show.nodes=TRUE, pch.nodes=21, cex.nodes=runif(10,1,3), 
        col.nodes="gray80", bg.nodes="gray90", lwd.nodes=2)

#different orientation
set.seed(120)
op = par(mar = c(0.5, 5, 0.5, 3))
arcplot(star_edges, ordering=sample(1:10), horizontal=FALSE,
        labels=paste("node",1:10,sep="-"),
        lwd.arcs=4*runif(10,.5,2), col.arcs=hsv(runif(9,0.6,0.8),alpha=0.4),
        show.nodes=TRUE, pch.nodes=21, cex.nodes=runif(10,1,3), 
        col.nodes="gray80", bg.nodes="gray90", lwd.nodes=2)
par(op)

par(mar = c(10,1,1,1))
madmen.edges <- get.edgelist(g)
arcplot(madmen.edges, show.nodes = TRUE, show.labels = TRUE,
        lwd.arcs=4*runif(10,.5,2), col.arcs=hsv(runif(9,0.5,0.9),alpha=0.4),
        col.nodes = "red", main = "Relationships in Mad Men",
        col.main = "navy")

```

